
server:
  port: 8081
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: dev
  application:
    name: user-service

  datasource:
    #mysql
    db1:
      # jdbc:mysql
      url: jdbc:mysql://192.168.175.129:3306/cvs_db?useUnicode=ture&characterEncoding=utf8mb4&useSSL=false&serverTimezone=UTC
      username: ray
      password: J_g123456
      driver-class-name: com.mysql.cj.jdbc.Driver

      # ?????
      # ?????????????
      initial-size: 5
      min-idle: 5
      max-active: 20
      # ?????????????
      max-wait: 5000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # ??????
      #        max-open-prepared-statements=
      validation-query: select 'x'
      validation-query-timeout: 5
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      # ???????????????????????????????
      time-between-eviction-runs-millis: 60000
      # ??????????????????????
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000
      # ?????????filters???????????
      filters: stat

  aop:
    auto: true
    # ????CGLIB???????(????)
    proxy-target-class: true


logging:
  config: classpath:log4j2.yml
  level:
    root: INFO
    javax.activation: info
    org.apache.catalina: INFO
    org.apache.commons.beanutils.converters: INFO
    org.apache.coyote.http11.Http11Processor: INFO
    org.apache.http: INFO
    org.apache.tomcat: INFO
    org.springframework: INFO
    com.chinamobile.cmss.bdpaas.resource.monitor: DEBUG